package kelompok6.tabuser;

import kelompok6.model.PaketModel;
import kelompok6.model.UserModel;
import kelompok6.repo.PaketRepo;
import java.util.UUID;

/**
 *
 * @author hafiz
 */
public class PaketData extends javax.swing.JFrame {

    /**
     * Creates new form PaketData
     */
    private static UserModel pesan;
    private PaketRepo paketDataRepo;

    public PaketData(UserModel session) {
        initComponents();
        pesan = session;
        this.paketDataRepo = new PaketRepo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        paket = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        beli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Pilih Paket");

        paket.setText("Paket Internet");

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih :", "20 Mbps Rp 239.000/bulan", "35 Mbps Rp 299.000/bulan", "50 Mbps Rp 349.000/bulan", "100 Mbps Rp 439.000/bulan" }));

        beli.setText("Beli");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(paket)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beli)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paket))
                .addGap(18, 18, 18)
                .addComponent(beli)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        // TODO add your handling code here:
        String selectedPaket = (String) level.getSelectedItem();
        if (selectedPaket != null && !selectedPaket.equals("Pilih :")) {
            PaketModel paket = new PaketModel(generateUniqueId(), selectedPaket, pesan.getUsername());
            boolean success = paketDataRepo.create(paket);
            if (success) {
                // Show success message
                javax.swing.JOptionPane.showMessageDialog(this, "Paket berhasil dibeli!");
            } else {
                // Show error message
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal membeli paket.");
            }
        } else {
            // Show warning message
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih paket terlebih dahulu.");
        }
    }//GEN-LAST:event_beliActionPerformed

    private String generateUniqueId() {
        return UUID.randomUUID().toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaketData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaketData(pesan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beli;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JLabel paket;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
